[package]
name = "ua-backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ua-protocol.workspace = true
tokio.workspace = true
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
